[package]
name = "huextract"
version = "0.1.0"
authors = ["echo-devim <devim@outlook.it>"]
edition = "2021"

[dependencies]
num_cpus = "1.7.0"
clap = { version = "3.2.18", features = [ "derive" ] }
tabled = "0.7.0"
